version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: finance_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: finance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - finance_network

  # Aplicação Python (FastAPI)
  app:
    build: .
    container_name: finance_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://admin:secret@postgres:5432/finance
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - finance_network

volumes:
  postgres_data:

networks:
  finance_network:
    driver: bridge